version: "3.9"

services: 
  mongo:
    container_name: mongo
    image: mongo:4.1
    ports: 
      - 27017:27017
    networks: 
      - app_express_network
    volumes: 
      - mongo_data:/data/db
  redis:
    container_name: redis
    image: redis:5
    ports: 
      - 6370:6379
    networks: 
      - app_express_network
    volumes: 
      - redis_data:/data
  app-express-docker:
    container_name: app-express-docker
    image: app-express:1.0.0
    # build: .
    ports: 
      - 3000:3000
    depends_on: 
      - mongo
      - redis
    environment: 
      - PORT=3000
      - NAME=Firas
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks: 
      -  app_express_network

networks: 
  app_express_network:
    name: app_express_network

volumes: 
  mongo_data:
    name: mongo_data
  redis_data:
    name: redis_data